CREATE TABLE senior_review_cases (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    submission_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    case_key VARCHAR(160) NOT NULL,
    case_type VARCHAR(32) NOT NULL,
    source_signal VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    priority VARCHAR(16) NOT NULL DEFAULT 'normal',
    reviewer_verdict_entry_id BIGINT,
    ai_overall_entry_id BIGINT,
    reviewer_id BIGINT,
    senior_reviewer_id BIGINT,
    resolution VARCHAR(48),
    reason TEXT,
    payload JSON,
    accountability JSON,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    resolved_at DATETIME(3),
    CONSTRAINT fk_senior_cases_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_senior_cases_task FOREIGN KEY (task_id) REFERENCES tasks(id),
    CONSTRAINT fk_senior_cases_reviewer_entry FOREIGN KEY (reviewer_verdict_entry_id) REFERENCES quality_ledger_entries(id),
    CONSTRAINT fk_senior_cases_ai_overall_entry FOREIGN KEY (ai_overall_entry_id) REFERENCES quality_ledger_entries(id),
    CONSTRAINT fk_senior_cases_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
    CONSTRAINT fk_senior_cases_senior_reviewer FOREIGN KEY (senior_reviewer_id) REFERENCES users(id),
    UNIQUE KEY uk_senior_cases_case_key (case_key),
    INDEX idx_senior_cases_queue (status, case_type, source_signal, created_at, id),
    INDEX idx_senior_cases_submission_status (submission_id, status),
    INDEX idx_senior_cases_task_status (task_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
